### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by marcklingen** [upleveled/mdx-local-link-checker#212]
I'd like to try mdx-local-link-checker for https://github.com/langfuse/langfuse-docs. Do you plan to release this under a FOSS license?

**Comment by karlhorky** [comment]
Ah sorry, it's MIT:

https://github.com/upleveled/mdx-local-link-checker/blob/1fda45d151a063a99f2080cf1e9e03165f41690c/package.json#L5

**Comment by karlhorky** [comment]
Also added a `LICENSE` file

https://github.com/upleveled/mdx-local-link-checker/blob/main/LICENSE

**Comment by karlhorky** [comment]
I'm not sure whether you want to use this though, I'm not maintaining it very much, and it still uses MDX v1.

You may want to look into other better-maintained alternatives, such as [`remark-validate-links`](https://github.com/remarkjs/remark-validate-links), maintained by @wooorm and other Unified people

The reason I created this alternative is because I was looking for root-relative link checking:

- https://github.com/remarkjs/remark-validate-links/issues/57
